const ADD_SUCCESS = "[movies] ADD_SUCCESS";
const DELETE_SUCCESS = "[movies] DELETE_SUCCESS";
const CHANGE_FILTER = "[movies] CHANGE_FILTER";
const FETCH_MOVIE_SUCCESS = "[movies] FETCH_MOVIE_SUCCESS";

const FETCH_REQUEST = "[movies] FETCH_REQUEST";
const FETCH_SUCCESS = "[movies] FETCH_SUCCESS";
const FETCH_ERROR = "[movies] FETCH_ERROR";

export default {
  FETCH_MOVIE_SUCCESS,
  ADD_SUCCESS,
  DELETE_SUCCESS,
  CHANGE_FILTER,
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR
};
